bluelibs/bluelibs

packages/x-ui-admin/DOCUMENTATION.md
packages/x-ui-admin/package.json
packages/x-ui-admin/src/react/models/Consumer.ts
packages/x-ui-admin/src/react/xutils/XForm.tsx
packages/x/BLUEPRINT.md
packages/x/package.json
packages/x/src/models/GenericModel.ts
packages/x/src/models/GraphQLInputModel.ts
packages/x/src/models/UICRUDModel.ts
packages/x/src/models/defs.ts
packages/x/src/studio/StudioWriter.ts
packages/x/src/studio/bridge/SanityChecker.ts
packages/x/src/studio/bridge/XBridge.ts
packages/x/src/studio/defs.ts
packages/x/src/studio/models/Field.ts
packages/x/src/studio/models/Relation.ts
packages/x/src/studio/shortcuts/index.ts
packages/x/src/utils/ModelUtils.ts
packages/x/src/writers/GraphQLCRUDWriter.ts
packages/x/src/writers/GraphQLInputWriter.ts
packages/x/templates/blueprint/partials/formXElement.tpl
packages/x/templates/blueprint/ui/i18n/generics.json

(x) (x-ui-admin) Support default values for backend models, inputs and forms.

---

packages/x/BLUEPRINT.md

`TextArea` instead of `Textarea`

Fix typo mismatching Antd component's name

---

scripts/bluelibs-package-replace

Fix - I have fixed a bug here where the src was being copied to the package.json.
Problem - When src is being copied to the package.json, the project stops considering the package as a node_module.

Bug - src being copied to package.json

---

packages/mongo-bundle/src/__tests__/behaviors/behaviors.test.ts
packages/mongo-bundle/src/behaviors/blameable.ts

If we do not have `userId` in the context of the event, the behaviour should _not_ replace `createdById` and `updatedById` (that we may pass in the input).
E.g.:
```ts
// I expect `createdById` to be `X`. At the moment, it'll be `null`
await collection.insertOne({
createdById: "X"
})
// I expect `createdById` to be `Y`
await collection.insertOne({
createdById: "X"
}, {
context: {
userId: "Y"
}
})
```

(fix) blameable behaviour should add/replace the fields only if userId exists in context

---

packages/core/src/__tests__/DI.test.ts
packages/core/src/di.ts

We already know that, if we are trying to get a service by a `class constructor`, even if it's not found, it will first set it in the container, then return it.
If the identifier is a `token` or a `string` and it's not found, we can't do the same, and the error should throw the correct name - `Token<TOKEN_NAME>` if the id is a token, otherwise directly the id.

(fix/di): throw a readable error when service is not found

---

packages/x-ui-admin/src/react/components/DatePicker.tsx
packages/x/templates/blueprint/partials/formXElement.tpl
packages/x/templates/blueprint/ui/collections/collection.ts.tpl

issue : [(https://github.com/bluelibs/bluelibs/issues/155)]
- fix the 01/01/1970 date instead of null in view/edit optionnal dates in ui-admin
- allow delete optionnal dates in ui admin

Issue 155 handle null date in ui admin

---

packages/x-ui-collections-bundle/DOCUMENTATION.md
packages/x-ui-collections-bundle/package.json
packages/x-ui-collections-bundle/src/__tests__/Collection.test.ts
packages/x-ui-collections-bundle/src/graphql/Collection.ts
packages/x-ui-collections-bundle/src/graphql/defs.ts
packages/x-ui-collections-bundle/src/react/hooks/useData.ts
packages/x-ui-collections-bundle/src/react/hooks/useLiveData.ts
packages/x-ui-collections-bundle/src/react/hooks/useSubscription.ts
packages/x/templates/microservice/backend/package.json

Flexible ways of working with ApolloClient

---

packages/x-ui-admin/src/react/components/RemoteSelect.tsx
packages/x/templates/blueprint/partials/formXElement.tpl

[https://github.com/bluelibs/bluelibs/issues/18](issue 18) allow clear on remote select for optionnal relations in ui-admin

Issue 18: unselect optionals relations in ui-admin 

---

packages/x-cron-bundle/src/__tests__/index.ts
packages/x-cron-bundle/src/defs.ts
scripts/bluelibs-package-replace

Changes :- 
Fix - I have added a type ParseStatic coming from library "later" (npm i --save-dev @types/later) to the param of function schedule in ICronConfig. 
Problem - It is a little puzzling for a new dev to get the structure of the parser and there is no direct linking of the parser to the package later. This will help the dev to know that parser comes from later and they can know more about it.

Added type to the parser in ICronConfig.schedule in package x-cron-bundle

---

packages/x-ui-admin/src/react/xutils/XForm.tsx

That PR allow falsy values to be considered as valid, as it is currently impossible to pass `false` or `null` or `""` or `0`

fix(xform): support falsy values as valid

---

packages/x-ui-collections-bundle/DOCUMENTATION.md
packages/x-ui-collections-bundle/src/graphql/Collection.ts

- Modify `collection.useQuery` and `collection.useMutation` signatures so they accept a single structured param instead of list of ordered params
- Set a query name to queries. By default, the same as the operationName, but can be customized by the developper. It allow refetching through query name string
- Set a default value to query bodies as `{ _id: 1 }`, making them optional
- Omit `query` and `mutation` from default apollo query and mutation options to avoid typescript to yell because of missing param, as it it directly provided by the `collection.use[query|mutation]`
Regarding setting `{ _id: 1 }` as default body, typescript was rasing an error as it considers the default value does not match overlap with `QueryBodyType<T>`, so I had to go for `body?: QueryBodyType<T> | { _id: …

feat(apollo-hooks): improve useQuery & useMutation API

---

packages/x/src/studio/bridge/XBridge.ts

[ISSUE 162 :](https://github.com/bluelibs/bluelibs/issues/162): fix "isRequired: false" not working for relation

Issue 162 relation requiredness not working

---

packages/x/src/utils/ModelUtils.ts

if the shared model field is not required, make it nullable yup validators

fix package x: issue 173 make the shared model validators nullable

---

packages/x-bundle/src/validators/ObjectId.validator.ts

the isValid on object id return true on string id, but not for ObjectId
fixes #225

fix x-bundle: objectId isValid returning false of objectId

---

packages/apollo-bundle/src/ApolloBundle.ts
packages/apollo-bundle/src/defs.ts

Idea: the way this was working before, you could only pass middlewares that applied for every route, e.g.:
```
middlewares: [
cors(),
...
]
```
But, if you wanted for example to apply a middleware only to a certain path, it wouldn't work. This way, you can pass in:
```
middlewares: [
cors(),
["/test", someMiddleware()],
["/another-test", [middleware1(), middleware2()]
]
```
Real use case: stripe webhooks need to have a "rawBody" on the request. By default, express doesn't have that. You need to use a middleware. And you don't want to use this middleware on any other router, other than the one for the webhook - because it's basically using 2x the memory. Hence, you could now do:
```
middlewares: [
["/stripe/webhooks", addRawBody],
express.json(),
]
```

(update): allow passing an array of [path, ...middlewares] as middleware

---

packages/x-ui-admin/src/react/components/AdminListItemRenderer.tsx
packages/x-ui-admin/src/react/components/RemoteSelect.tsx
packages/x/src/models/UICRUDModel.ts
packages/x/src/studio/models/App.ts
packages/x/src/studio/models/Collection.ts
packages/x/src/studio/models/Relation.ts
packages/x/src/studio/models/SharedModel.ts

fixed the [https://github.com/bluelibs/bluelibs/issues/169](issue 169),
allowing the representedBy to be nested, example: representedBy ='profile.job.jobTitle'
fixes #169

fix x and x-ui-admin: allow representedBy to be nested

---

packages/x/src/writers/CollectionLinkWriter.ts

the alreadyexportlink check wasnt working properly if 2 link start with same string, I added ":" to ensure the end of variable name and start of the type 
closes #217

fix x: fix exportlink condition check when generating links

---

packages/x-ui-collections-bundle/src/graphql/Collection.ts

It's reading the HTML document, inducing a cyclic error in apollo client. This is common & important enough to be caugth in a a unit test :)
Found by https://github.com/matthieujabbour/

fix(x-ui): remove document from deleteOne

---

packages/x-ui-react-bundle/src/XUIReactBundle.ts

closes #191 
if this solution is ok, I need to do it on next-ui too

[R] fix (smart,x-ui-react-bundle): handle error use smart before kernel init

---

packages/smart/src/Smart.ts
packages/smart/src/hooks.ts

The idea is that we don't inform people about the fact that Smarts have methods with the names of "subscribe" and "unsubscribe"; if you're not going to check for them, or if the IDE doesn't help you, you can end up overriding these functions and `useSmart` will not react to changes, hence you will be sad. (true story)
My solution was to prefix the methods with two underscores.

(fix): prefix (un)subscribe with underscores

---

packages/x/src/writers/ServiceWriter.ts

Imagine wanting to run a test, using `npm run test`. In the index file of `__tests__`, it will try to import the `ts` file:
```
FAIL  dist/__tests__/index.js
● Test suite failed to run
Cannot find module './Business.service.test.ts' from 'dist/bundles/AppBundle/__tests__/index.js'
Require stack:
dist/bundles/AppBundle/__tests__/index.js
dist/__tests__/index.js
1 | import "./User.service.test";
> 2 | import "./Business.service.test.ts";
| ^
3 | // import { container } from "../../../__tests__/ecosystem";
4 |
5 | test("dummy", () => {
```
Solution: remove the ".ts" extension from the import line

fix(service writer): do not import test files with extension ".ts"

---

packages/smart/package.json

The idea is that we encounter issues when we try to simply do `npm install` in `x-ui-react-router-bundle`, and the issue seems to come from `@bluelibs/smart` that allows `react` as peerDependency with `>=17.0.2`. This way, it tries to install `react@18.2.0` and it has conflicts with the rest of the packages. ...if I understood right.
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: @bluelibs/x-ui-react-router-bundle@1.0.4
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   peer react@">=17.0.2" from @bluelibs/smart@1.0.1
npm ERR!   node_modules/@bluelibs/smart
npm ERR!     peer @bluelibs/smart@"^1.0.0" from @bluelibs/x-ui-guardian-bundle@1.3.1
npm ERR!     node_modules/@bluelibs/x-ui-guardian-bundle
npm ERR! …
```

fix: use "^" instead of ">=" for react peer

---

packages/core/src/models/Listener.ts

At the moment, we have the following issue:
```
@On(MyEvent, {
filter: (e) => ... // e is Event<any>. Instead, it should be MyEvent
})
```
This PR solves this issue.

feat: add <T> for "On"

---

.gitignore
packages/nova/DOCUMENTATION.md
packages/nova/src/__tests__/connection.ts
packages/nova/src/__tests__/integration/index.ts
packages/nova/src/core/defs.ts
packages/nova/src/core/query/Linker.ts
packages/nova/src/core/query/hypernova/processDirectNode.ts
packages/nova/src/core/query/hypernova/processRecursiveNode.ts
packages/nova/src/core/query/hypernova/processVirtualNode.ts
packages/nova/src/core/query/lib/createFilters.ts
packages/nova/src/core/query/nodes/CollectionNode.ts
packages/nova/src/core/quickLinkers.ts

In the LinkCollectionOptions, I added a new property named `foreignField` aside from the `field` property. 
It allows customization of the foreign field of a nova relation instead of the hardcoded `_id` foreign field

[R] (nova) Add foreignField when defining relations

---

packages/apollo-bundle/src/ApolloBundle.ts
packages/apollo-bundle/src/declarations.ts
packages/apollo-bundle/src/defs.ts
packages/ui-apollo-bundle/package.json
packages/ui-apollo-bundle/src/events/index.ts
packages/ui-apollo-bundle/src/graphql/ApolloClient.ts
packages/ui-apollo-bundle/src/graphql/utils/createApolloLink.ts
packages/x/templates/microservice/frontend-next/package.json

In the new version `@bluelibs/apollo-bundle@2.X` switched from `subscriptions-transport-ws` to `graphql-ws` to handle Subscriptions.
But the new implementation does not seems complete. The client (`@bluelibs/ui-apollo-bundle`) still uses the older `subscriptions-transport-ws`. And on the server the GraphQL context is not properly initialized for Subscription resolvers.
I tried patching the package on my side, and came to do these modifications in order to have a fonctionning websocket server for GraphQL Subscriptions.
I open a Pull Request here in order to share the modifications, if my problem is found to be a real bug on bluelibs, fell free to  consider this for merging.
Else if I was the only having this error, I will close this PR and try to find where in my installation the problem …

Replace subscriptions-transport-ws with graphql-ws

---

packages/mongo-bundle/src/behaviors/validate.ts

When using the validator bundle, it seems like this caused an infinite loop, since the wrapped findOneAndUpdate call called itself over and over again.
With these 2 changes I still get the following error:
```
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
MongoTransactionError: Cannot call abortTransaction twice
at ClientSession.abortTransaction (/Users/flo/dev/ogment-2/backend/node_modules/mongodb/src/sessions.ts:613:13)
at ClientSession.withTransaction (/Users/flo/dev/ogment-2/backend/node_modules/mongodb/src/sessions.ts:794:24)
at processTicksAndRejections (node:internal/process/task_queues:95:5)
at async DatabaseService.transact …
```

Prevent infinite loop when wrapping findOneAndUpdate
